name: mars
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_colorpicker: ^0.2.6
  pie_chart: ^1.2.0
  audioplayers: ^0.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/peak.mp3
    - assets/intro.mp3
    - assets/test.mp3
    - assets/breath.mp3
    - assets/mind.mp3
    - assets/body.mp3
    - assets/sound.mp3
    - assets/walk.mp3
    - assets/aware.mp3
    - assets/moodsurf.jpg
    - assets/meditate.png
    - assets/mars.png
    - assets/mars_load.png
    - assets/moodsurf_logo.png
    - assets/imagine.png
    - assets/imagine_1.png
    - assets/imagine_2.png
    - assets/imagine_3.png
    - assets/imagine_4.png
    - assets/imagine_5.png
    - assets/notice.png
    - assets/notice_1.png
    - assets/joy.png
    - assets/moodsurf_1.png
    - assets/moodsurf_2.png
    - assets/moodsurf_3.png
    - assets/moodsurf_4.png
    - assets/moodsurf_5.png
    - assets/moodsurf_6.png
    - assets/moodsurf_7.png
    - assets/meditate_1.png
    - assets/meditate_2.png
    - assets/moodsurf_load_screen.png
    - assets/meditate_load_screen.png
    - assets/notice_load_screen.png
    - assets/joy_load_screen.png
    - assets/imagine_load_screen.png
    - assets/joy_0.png
    - assets/joy_1.png
    - assets/moodsurf_0_begin_page.mp3
    - assets/moodsurf_1_imagine_page.mp3
    - assets/moodsurf_2_imagine_page.mp3
    - assets/moodsurf_3_imagine_page.mp3
    - assets/moodsurf_4_some_page.mp3
    - assets/moodsurf_5_thinking_page.mp3
    - assets/moodsurf_6_like_page.mp3
    - assets/imagine_0_begin_page.mp3
    - assets/imagine_1_you_page.mp3
    - assets/imagine_2_take_page.mp3
    - assets/imagine_3_imaging_page.mp3
    - assets/imagine_4_color_page.mp3
    - assets/imagine_5_shape_page.mp3
    - assets/imagine_6_remember_page.mp3
    - assets/imagine_7_using_page.mp3
    - assets/imagine_8_like_page.mp3
    - assets/meditate_0_begin_page.mp3
    - assets/meditate_1_menu_page.mp3
    - assets/meditate_3_like_page.mp3
    - assets/notice_0_begin_page.mp3
    - assets/notice_1_this_page.mp3
    - assets/notice_2_experiencing_page.mp3
    - assets/notice_3_take_page.mp3

    - assets/notice_3_take_page_tension.mp3
    - assets/notice_3_take_page_calmness.mp3
    - assets/notice_3_take_page_shakiness.mp3
    - assets/notice_3_take_page_stillness.mp3
    - assets/notice_3_take_page_pain.mp3
    - assets/notice_3_take_page_warmth.mp3
    - assets/notice_3_take_page_tightness.mp3
    - assets/notice_3_take_page_sweatiness.mp3
    - assets/notice_3_take_page_restlessness.mp3
    - assets/notice_3_take_page_fluttering.mp3
    - assets/notice_3_take_page_irritability.mp3
    - assets/notice_3_take_page_soreness.mp3
    - assets/notice_3_take_page_other_physical_sensation.mp3


    - assets/notice_4_one_page_tension.mp3
    - assets/notice_4_one_page_calmness.mp3
    - assets/notice_4_one_page_shakiness.mp3
    - assets/notice_4_one_page_stillness.mp3
    - assets/notice_4_one_page_pain.mp3
    - assets/notice_4_one_page_warmth.mp3
    - assets/notice_4_one_page_tightness.mp3
    - assets/notice_4_one_page_sweatiness.mp3
    - assets/notice_4_one_page_restlessness.mp3
    - assets/notice_4_one_page_fluttering.mp3
    - assets/notice_4_one_page_irritability.mp3
    - assets/notice_4_one_page_soreness.mp3
    - assets/notice_4_one_page_other_physical_sensation.mp3

    - assets/notice_5_strong_page_tension.mp3
    - assets/notice_5_strong_page_calmness.mp3
    - assets/notice_5_strong_page_shakiness.mp3
    - assets/notice_5_strong_page_stillness.mp3
    - assets/notice_5_strong_page_pain.mp3
    - assets/notice_5_strong_page_warmth.mp3
    - assets/notice_5_strong_page_tightness.mp3
    - assets/notice_5_strong_page_sweatiness.mp3
    - assets/notice_5_strong_page_restlessness.mp3
    - assets/notice_5_strong_page_fluttering.mp3
    - assets/notice_5_strong_page_irritability.mp3
    - assets/notice_5_strong_page_soreness.mp3
    - assets/notice_5_strong_page_other_physical_sensation.mp3

    - assets/notice_6_feel_page_tension.mp3
    - assets/notice_6_feel_page_calmness.mp3
    - assets/notice_6_feel_page_shakiness.mp3
    - assets/notice_6_feel_page_stillness.mp3
    - assets/notice_6_feel_page_pain.mp3
    - assets/notice_6_feel_page_warmth.mp3
    - assets/notice_6_feel_page_tightness.mp3
    - assets/notice_6_feel_page_sweatiness.mp3
    - assets/notice_6_feel_page_restlessness.mp3
    - assets/notice_6_feel_page_fluttering.mp3
    - assets/notice_6_feel_page_irritability.mp3
    - assets/notice_6_feel_page_soreness.mp3
    - assets/notice_6_feel_page_other_physical_sensation.mp3

    - assets/notice_7_mood_page_tension.mp3
    - assets/notice_7_mood_page_calmness.mp3
    - assets/notice_7_mood_page_shakiness.mp3
    - assets/notice_7_mood_page_stillness.mp3
    - assets/notice_7_mood_page_pain.mp3
    - assets/notice_7_mood_page_warmth.mp3
    - assets/notice_7_mood_page_tightness.mp3
    - assets/notice_7_mood_page_sweatiness.mp3
    - assets/notice_7_mood_page_restlessness.mp3
    - assets/notice_7_mood_page_fluttering.mp3
    - assets/notice_7_mood_page_irritability.mp3
    - assets/notice_7_mood_page_soreness.mp3
    - assets/notice_7_mood_page_other_physical_sensation.mp3

#    - assets/notice_4_one_page.mp3
#    - assets/notice_5_strong_page.mp3
#    - assets/notice_6_feel_page.mp3
#    - assets/notice_7_mood_page.mp3
    - assets/notice_8_notcing_page.mp3
    - assets/notice_9_like_page.mp3
    - assets/joy_0_begin_page.mp3
    - assets/joy_1_deep_page.mp3
    - assets/joy_2_slowly_page.mp3
    - assets/joy_3_now_page.mp3
    - assets/joy_4_select_page.mp3
    - assets/joy_6_complete_page.mp3
    - assets/joy_7_whenever_page.mp3
    - assets/joy_8_like_page.mp3

#    - assets/imagine_logo.png
#    - assets/notice_white.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: 'Lexend Exa'
      fonts:
        - asset: assets/LexendExa-Regular.ttf
    - family: 'Lexend Deca'
      fonts:
        - asset: assets/LexendDeca-Regular.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
